// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import("element-plus/es")["ElCarousel"]
    ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"]
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloInject: typeof import('./components/HelloInject.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HelloWorldBro: typeof import('./components/HelloWorldBro.vue')['default']
    Loading: typeof import('./components/myLoading/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
